Adds distinction between IERROR/XERROR.
IERROR: Internal error, need to see source filename and line number.
XERROR: Error for user - no source filename or line number.